services:
  eureka-server:
    image: shashank092/revtickets-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - revtickets-network
    restart: unless-stopped

  api-gateway:
    image: shashank092/revtickets-gateway:latest
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - revtickets-network
    restart: unless-stopped

  user-service:
    image: shashank092/revtickets-user:latest
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - revtickets-network
    restart: unless-stopped

  movie-service:
    image: shashank092/revtickets-movie:1
    container_name: movie-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - revtickets-network
    restart: unless-stopped

  venue-service:
    image: shashank092/revtickets-venue:latest
    container_name: venue-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - revtickets-network
    restart: unless-stopped

  booking-service:
    image: shashank092/revtickets-booking:latest
    container_name: booking-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - revtickets-network
    restart: unless-stopped

  payment-service:
    image: shashank092/revtickets-payment:latest
    container_name: payment-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - revtickets-network
    restart: unless-stopped

  frontend:
    image: shashank092/revtickets-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - revtickets-network
    restart: unless-stopped

networks:
  revtickets-network:
    driver: bridge